### ISSUE TITLE
kubectl 管理多个集群

### ISSUE THREAD

**Issue by alastairruhm** [alastairruhm/alastairruhm.github.io#9]
可以在 kube config 配置文件中配置多个集群，如下，

```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority: /Users/leon/kubernetes/auth/ca.pem
    server: https://192.168.1.100:6443
  name: default-cluster
- cluster:
    certificate-authority: /Users/leon/.minikube/ca.crt
    server: https://192.168.99.100:8443
  name: minikube
contexts:
- context:
    cluster: default-cluster
    user: default-admin
  name: default-system
- context:
    cluster: minikube
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: default-admin
  user:
    client-certificate: /Users/leon/kubernetes/auth/admin.pem
    client-key: /Users/leon/kubernetes/auth/admin-key.pem
- name: minikube
  user:
    client-certificate: /Users/leon/.minikube/apiserver.crt
    client-key: /Users/leon/.minikube/apiserver.key
```

注意在 `context` 配置 cluster 和 user 的 Match 关系

```yaml
- context:
    cluster: minikube
    user: minikube
  name: minikube
```

切换的步骤：

1.检查当前的 context

```bash
$ kubectl config current-context
minikube
```

2.切换 context

```
$ kubectl config use-context default-system
Switched to context "default-system".
```

3.检查是否完成切换

```
$ kubectl config current-context
default-system
```
